In [6]:

from keras_preprocessing import image

# model = tf.keras.models.load_model(r'C:\Users\91992\Machine_learning\face_recognization\facefeature_inception.h2')


face_cascade = cv2.CascadeClassifier(r"C:\Users\91992\Machine_learning\face_recognization\haarcascades\haarcascade_frontalface_default.xml")

def face_extractor(img):

    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')

        img_array = np.array(im)
                    
        img_array = np.expand_dims(img_array, axis=0)
        img_array = img_array.astype(np.float16)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1] > 0.5):
            name='Rishav'
#         cv2.putText(frame,pred[0][1], (10, 10), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        cv2.putText(frame,name, (60, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        
    else:
        cv2.putText(frame,"no matching", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[1.0000000e+00 6.1999355e-23]]
[[1.0000000e+00 5.4143044e-31]]
[[1.000000e+00 5.698179e-15]]
[[0.85277754 0.14722243]]
[[2.7709694e-08 1.0000000e+00]]
[[2.1622376e-10 1.0000000e+00]]
[[1.0000000e+00 1.7379666e-14]]
[[1.7052591e-17 1.0000000e+00]]
[[1.9947258e-06 9.9999797e-01]]
[[1.52306275e-05 9.99984741e-01]]
[[9.9999547e-01 4.5221368e-06]]
[[9.9999893e-01 1.1184436e-06]]
[[1.00000e+00 1.62355e-08]]
[[2.1628941e-04 9.9978369e-01]]
[[0.98105526 0.01894478]]
[[0.9927596  0.00724042]]
[[2.6541066e-04 9.9973458e-01]]
[[2.1203450e-06 9.9999785e-01]]
[[0.37977198 0.62022805]]
[[0.7513029  0.24869712]]
[[1.000000e+00 8.897066e-09]]
[[0.99775046 0.0022495 ]]
[[4.5240045e-06 9.9999547e-01]]
[[0.17990324 0.82009685]]
[[5.5070206e-05 9.9994493e-01]]
[[9.9999619e-01 3.7973073e-06]]
[[9.9999809e-01 1.9040854e-06]]
[[9.994123e-01 5.876746e-04]]
[[0.7393253  0.26067474]]
[[1.0000000e+00 1.8050715e-09]]
[[1.0000000e+00 1.3860442e-12]]
[[1.000000e+00 6.660186e-10]]
[[5.4684915e-07 9.9999940e-01]]
[[

In [2]:
from PIL import Image
from tensorflow.keras.applications.inception_v3 import InceptionV3
import base64
from io import BytesIO
import json
import random
import keras_preprocessing
import cv2
import tensorflow as tf
# from tensorflow.keras.models import load_model
from tensorflow import keras
import numpy as np


In [3]:
model = tf.keras.models.load_model(r'C:\Users\91992\Machine_learning\face_recognization\facefeature_inception.h5')

In [4]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 111, 111, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 111, 111, 32) 0           batch_normalization[0][0]        
______________________________________________________________________________________________